kind = "web"
previewPath = "/"
title = "stitchnem"
version = "1.0.0"
id = "artifacts/stitchnem"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25259

[services.development]
run = "pnpm --filter @workspace/stitchnem run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/stitchnem", "run", "build" ]
serve = "static"
publicDir = "artifacts/stitchnem/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25259"
BASE_PATH = "/"
